"""Small Ollama chat adapter for the Agentanyl feedback loop.

Ollama exposes a conversation API, not hidden activations. This adapter therefore
delivers Agentanyl's rendered signal as an auxiliary user message on the next
request. The controller, evaluator, state ledger, and duplicate protection stay
in Agentanyl; Ollama only performs model inference.
"""
from __future__ import annotations

import json
from pathlib import Path
import time
from urllib.request import Request, urlopen

from .loop import db_connect, load_config, run


class OllamaAgent:
    """Conversation client with one-turn-delayed Agentanyl feedback."""

    def __init__(self, model: str, config_path: str | Path, db_path: str | Path,
                 *, base_url: str = "http://127.0.0.1:11434", session: str = "ollama"):
        self.model = model
        self.config_path = Path(config_path)
        self.config = load_config(self.config_path)
        self.db = db_connect(db_path)
        self.base_url = base_url.rstrip("/")
        self.session = session
        self.messages: list[dict] = []
        self.pending_signal: str | None = None
        self.turn_index = 0

    def close(self) -> None:
        self.db.close()

    def _chat(self) -> str:
        request = Request(
            self.base_url + "/api/chat",
            data=json.dumps({"model": self.model, "messages": self.messages,
                             "stream": False}).encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )
        with urlopen(request, timeout=300) as response:
            payload = json.load(response)
        message = payload.get("message")
        if not isinstance(message, dict) or not isinstance(message.get("content"), str):
            raise ValueError("Ollama response did not contain message.content")
        content = message["content"]
        self.messages.append({"role": "assistant", "content": content})
        return content

    def turn(self, prompt: str) -> dict:
        """Send one user task and evaluate the completed response.

        A signal generated by the previous response is inserted immediately
        before this turn's user prompt. It is recorded in the returned delivery
        object and in Agentanyl's trace database.
        """
        if not isinstance(prompt, str) or not prompt:
            raise ValueError("prompt must be a nonempty string")
        delivered = self.pending_signal
        if delivered:
            self.messages.append({"role": "user", "content": delivered})
            self.pending_signal = None
        self.messages.append({"role": "user", "content": prompt})
        answer = self._chat()
        self.turn_index += 1
        event = {
            "event": "turn_end", "launch": "ollama", "harness": "ollama",
            "session": self.session, "text": answer,
            "prompt": prompt, "ts": time.time(),
        }
        delivery = run(self.config, event, self.db, str(self.config_path))
        if delivery.get("status") == "signal":
            self.pending_signal = delivery["message"]
        return {"turn": self.turn_index, "prompt": prompt, "answer": answer,
                "delivered_previous": delivered, "delivery": delivery}


__all__ = ["OllamaAgent"]
